// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currencry string
	CreatedAt time.Time
}

type Entry struct {
	ID         int64
	AcccountID int64
	Amount     int64
	CreatedAt  time.Time
}

type Transfer struct {
	ID             int64
	FromAcccountID int64
	ToAcccountID   int64
	Amount         int64
	CreatedAt      time.Time
}
